// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/keeper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretKeeper_RegisterUser_FullMethodName        = "/keeper.SecretKeeper/RegisterUser"
	SecretKeeper_AuthUser_FullMethodName            = "/keeper.SecretKeeper/AuthUser"
	SecretKeeper_GetUserStoredData_FullMethodName   = "/keeper.SecretKeeper/GetUserStoredData"
	SecretKeeper_UpdateLoginPassword_FullMethodName = "/keeper.SecretKeeper/UpdateLoginPassword"
	SecretKeeper_UpdateTextData_FullMethodName      = "/keeper.SecretKeeper/UpdateTextData"
	SecretKeeper_UpdateBankCard_FullMethodName      = "/keeper.SecretKeeper/UpdateBankCard"
	SecretKeeper_UpdateBinaryData_FullMethodName    = "/keeper.SecretKeeper/UpdateBinaryData"
	SecretKeeper_DeleteStoredData_FullMethodName    = "/keeper.SecretKeeper/DeleteStoredData"
)

// SecretKeeperClient is the client API for SecretKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative go-secret-keeper/internal/proto/keeper.proto
type SecretKeeperClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AuthUserResponse, error)
	GetUserStoredData(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetUserStoredDataResponse, error)
	// rpc UpdateStoredData(UpdateStoredDataRequest)returns(google.protobuf.Empty);
	UpdateLoginPassword(ctx context.Context, in *UpdateLoginPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateTextData(ctx context.Context, in *UpdateTextDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateBankCard(ctx context.Context, in *UpdateBankCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateBinaryData(ctx context.Context, in *UpdateBinaryDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteStoredData(ctx context.Context, in *DeleteStoredDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type secretKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretKeeperClient(cc grpc.ClientConnInterface) SecretKeeperClient {
	return &secretKeeperClient{cc}
}

func (c *secretKeeperClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, SecretKeeper_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AuthUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthUserResponse)
	err := c.cc.Invoke(ctx, SecretKeeper_AuthUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) GetUserStoredData(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetUserStoredDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserStoredDataResponse)
	err := c.cc.Invoke(ctx, SecretKeeper_GetUserStoredData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) UpdateLoginPassword(ctx context.Context, in *UpdateLoginPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SecretKeeper_UpdateLoginPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) UpdateTextData(ctx context.Context, in *UpdateTextDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SecretKeeper_UpdateTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) UpdateBankCard(ctx context.Context, in *UpdateBankCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SecretKeeper_UpdateBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) UpdateBinaryData(ctx context.Context, in *UpdateBinaryDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SecretKeeper_UpdateBinaryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeeperClient) DeleteStoredData(ctx context.Context, in *DeleteStoredDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SecretKeeper_DeleteStoredData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretKeeperServer is the server API for SecretKeeper service.
// All implementations must embed UnimplementedSecretKeeperServer
// for forward compatibility.
//
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative go-secret-keeper/internal/proto/keeper.proto
type SecretKeeperServer interface {
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	AuthUser(context.Context, *AuthUserRequest) (*AuthUserResponse, error)
	GetUserStoredData(context.Context, *emptypb.Empty) (*GetUserStoredDataResponse, error)
	// rpc UpdateStoredData(UpdateStoredDataRequest)returns(google.protobuf.Empty);
	UpdateLoginPassword(context.Context, *UpdateLoginPasswordRequest) (*emptypb.Empty, error)
	UpdateTextData(context.Context, *UpdateTextDataRequest) (*emptypb.Empty, error)
	UpdateBankCard(context.Context, *UpdateBankCardRequest) (*emptypb.Empty, error)
	UpdateBinaryData(context.Context, *UpdateBinaryDataRequest) (*emptypb.Empty, error)
	DeleteStoredData(context.Context, *DeleteStoredDataRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSecretKeeperServer()
}

// UnimplementedSecretKeeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretKeeperServer struct{}

func (UnimplementedSecretKeeperServer) RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedSecretKeeperServer) AuthUser(context.Context, *AuthUserRequest) (*AuthUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthUser not implemented")
}
func (UnimplementedSecretKeeperServer) GetUserStoredData(context.Context, *emptypb.Empty) (*GetUserStoredDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserStoredData not implemented")
}
func (UnimplementedSecretKeeperServer) UpdateLoginPassword(context.Context, *UpdateLoginPasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLoginPassword not implemented")
}
func (UnimplementedSecretKeeperServer) UpdateTextData(context.Context, *UpdateTextDataRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTextData not implemented")
}
func (UnimplementedSecretKeeperServer) UpdateBankCard(context.Context, *UpdateBankCardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBankCard not implemented")
}
func (UnimplementedSecretKeeperServer) UpdateBinaryData(context.Context, *UpdateBinaryDataRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBinaryData not implemented")
}
func (UnimplementedSecretKeeperServer) DeleteStoredData(context.Context, *DeleteStoredDataRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStoredData not implemented")
}
func (UnimplementedSecretKeeperServer) mustEmbedUnimplementedSecretKeeperServer() {}
func (UnimplementedSecretKeeperServer) testEmbeddedByValue()                      {}

// UnsafeSecretKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretKeeperServer will
// result in compilation errors.
type UnsafeSecretKeeperServer interface {
	mustEmbedUnimplementedSecretKeeperServer()
}

func RegisterSecretKeeperServer(s grpc.ServiceRegistrar, srv SecretKeeperServer) {
	// If the following call pancis, it indicates UnimplementedSecretKeeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretKeeper_ServiceDesc, srv)
}

func _SecretKeeper_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretKeeper_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretKeeper_AuthUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).AuthUser(ctx, req.(*AuthUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_GetUserStoredData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).GetUserStoredData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretKeeper_GetUserStoredData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).GetUserStoredData(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_UpdateLoginPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLoginPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).UpdateLoginPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretKeeper_UpdateLoginPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).UpdateLoginPassword(ctx, req.(*UpdateLoginPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_UpdateTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTextDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).UpdateTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretKeeper_UpdateTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).UpdateTextData(ctx, req.(*UpdateTextDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_UpdateBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBankCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).UpdateBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretKeeper_UpdateBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).UpdateBankCard(ctx, req.(*UpdateBankCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_UpdateBinaryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBinaryDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).UpdateBinaryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretKeeper_UpdateBinaryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).UpdateBinaryData(ctx, req.(*UpdateBinaryDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretKeeper_DeleteStoredData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoredDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretKeeperServer).DeleteStoredData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretKeeper_DeleteStoredData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretKeeperServer).DeleteStoredData(ctx, req.(*DeleteStoredDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretKeeper_ServiceDesc is the grpc.ServiceDesc for SecretKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keeper.SecretKeeper",
	HandlerType: (*SecretKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _SecretKeeper_RegisterUser_Handler,
		},
		{
			MethodName: "AuthUser",
			Handler:    _SecretKeeper_AuthUser_Handler,
		},
		{
			MethodName: "GetUserStoredData",
			Handler:    _SecretKeeper_GetUserStoredData_Handler,
		},
		{
			MethodName: "UpdateLoginPassword",
			Handler:    _SecretKeeper_UpdateLoginPassword_Handler,
		},
		{
			MethodName: "UpdateTextData",
			Handler:    _SecretKeeper_UpdateTextData_Handler,
		},
		{
			MethodName: "UpdateBankCard",
			Handler:    _SecretKeeper_UpdateBankCard_Handler,
		},
		{
			MethodName: "UpdateBinaryData",
			Handler:    _SecretKeeper_UpdateBinaryData_Handler,
		},
		{
			MethodName: "DeleteStoredData",
			Handler:    _SecretKeeper_DeleteStoredData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/keeper.proto",
}
