syntax = "proto3";

package keeper;
option go_package = "secret-keeper/internal/secretkeeperpb";


import "google/protobuf/empty.proto";
// Request Response CheckDatabaseConnection
service SecretKeeper {
	rpc RegisterUser(RegisterUserRequest)returns(RegisterUserResponse);
	rpc AuthUser(AuthUserRequest)returns(AuthUserResponse);
	rpc GetListStoredData(GetListStoredDataRequest)returns(GetListStoredDataResponse);
	rpc GetPasswordByLogin(GetPasswordByLogin)returns(GetPasswordByLogin);
	rpc GetTextData(GetTextDataRequest)returns(GetTextDataResponse);
	rpc GetBankCardByNumber(GetBankCardByNumberRequest)returns(GetBankCardByNumberResponse);
	rpc GetBinaryData(GetBinaryData)returns(GetBinaryData);
	rpc UpdateData() returns();
}

message RegisterUserRequest {
	string username = 1;
	string user_password = 2;
}

message RegisterUserResponse {
	string token_jwt = 1;
}

message AuthUserRequest{
	string username = 1;
	string user_password = 2;
}

message AuthUserResponse {
	string token_jwt = 1;
}

message GetPasswordByLoginRequest{
	string username = 1;
	string metadata = 2;
}

message GetPasswordByLoginResponse{
	string password = 1;
}

message GetDataResponse{
	
}